import { ICONSPATH } from "../APIS/IconsApi.js";

import { ADDPACKAGE } from "../PACKAGES/ADDPACKAGE/AddPackage.js";

import { ADDSTORAGE } from "../PACKAGES/ADDSTORAGE/AddStorage.js";

import { CHOOSEFILE, CHOOSENFILE } from "../PACKAGES/CHOOSEFILE/ChooseFile.js";

import { CLEARCOMPONENTS } from "../PACKAGES/CLEARCOMPONENTS/ClearComponents.js";

import { DELETESTORAGE } from "../PACKAGES/DELETESTORAGE/DeleteStorage.js";

import { DISPLAYDATA } from "../PACKAGES/DISPLAYDATA/DisplayData.js";

import { GETPACKAGE } from "../PACKAGES/GETPACKAGE/GetPackage.js";

import { GETSTORAGE } from "../PACKAGES/GETSTORAGE/GetStorage.js";

import { OPERATINGSYSTEM } from "../PACKAGES/OPERATIONCHECKER/OperationChecker.js";

import { POSTPACKAGE } from "../PACKAGES/POSTPACKAGE/PostPage.js";

import { REMOVESTORAGE } from "../PACKAGES/REMOVESTORAGE/RemoveStorage.js";

import { SHUFFLEDATA } from "../PACKAGES/SHUFFLEDATA/ShuffleData.js";

import { STYLED } from "../PACKAGES/STYLECOMPONENTS/StyleComponents.js";

import { ZOOMEFFECT } from "../PACKAGES/ZOOMEFFECT/ZoomEffect.js";

export{ICONSPATH,ADDPACKAGE,ADDSTORAGE,CHOOSEFILE,CHOOSENFILE,CLEARCOMPONENTS,DELETESTORAGE,DISPLAYDATA,GETPACKAGE,GETSTORAGE,OPERATINGSYSTEM,POSTPACKAGE,REMOVESTORAGE,STYLED,SHUFFLEDATA,ZOOMEFFECT}