import { ANDROIDLOGINPAGE } from "../LOGINPAGE/LoginPage.js";

const ANDROIDLOGOUTPAGE=(DIV,ADD,CLEAR,DISPLAY,ICONS,ADVANCE)=>{

    ADVANCE.REMOVESTORAGE('local','User');

    ADVANCE.REMOVESTORAGE('local','Premium');

    ADVANCE.REMOVESTORAGE('local','ParentalControlPin');

    ADVANCE.REMOVESTORAGE('local','AppPlayer');

    ADVANCE.REMOVESTORAGE('local','Privacy');

    ADVANCE.DELETESTORAGE('');

    ANDROIDLOGINPAGE(DIV,ADD,CLEAR,DISPLAY,ICONS,ADVANCE);

}

export{ANDROIDLOGOUTPAGE};