const LOGINAPI='https://script.googleusercontent.com/macros/echo?user_content_key=FrRUgOqf3VCxfuxM0DsEGIbG4WJO7w6hzhW1PCjyGpXHv6s8QNW9KDYTTTgy6pgCb5mZAG3Xu4iV4iuzcr_Qqk6eBXABdmilm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnC6FucGMPJDFo1vc7xUPuBYfMxKKRVodlYbzMzCKjeT4wckk24qUxiiMTCfM25DUQrZEICugxLUlQqQnl1bAwtTGq09GeSHZLQ&lib=MVjI1E0k9FXqhcOE_zgy4zMSoMAbC-O1l';

const ADVERTSAPI='https://script.googleusercontent.com/macros/echo?user_content_key=_FX5ZQszJTEaomt8vckUHZsbkYxs62AufD0I_MQsx3CbUUTVaKGIsVxa81TnknHluq86maqwEExLI40xhzNBlzOz-3r4R4-bm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnMm14i5DlW2geHNLZPLM52lioxem8eoSFBSyqk07ilFVS9WmMu3qXi9UzJNBBOXMuvjnNWGKIg_NChXL98fYqjXBIndAU2515A&lib=M6UN6W68Hd-KGliVyb1fwhsSoMAbC-O1l';

const ANIMATIONAPI='https://script.googleusercontent.com/macros/echo?user_content_key=B9fqEvmtnCCHwDCnZ-5sSu71toz4MzoTxrf315wtfIEHuxNM5Cu_h2HZT9xGl4tilFh7FjC1IIzjdkEWCGntE5bEmMeoK2vDm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnOAkcG97VzAwakN9YYUAFyQRPRZikRmdTl4f6LGzID4_cBMsR6pkaEiX2dzEcjXvsk_3lB6gifItW4UIJWMKj6fcYTTmUjnljQ&lib=Mr4rCsHrrWb3rNW8Tj5K_BsSoMAbC-O1l';

const MOVIESAPI='https://script.googleusercontent.com/macros/echo?user_content_key=-wyaXIk2LhJxjEot2-J8yJrsUAthsjEuSflUQbGS5zlpBYnPiCfK_ZVdaUyv6e-LaeiPvJ-UFmRzcEWHc5q_jB7hFYJAp46rm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnDpdlXrhatqbPKt7BRJFGGfTbTFKzkRnaU9faRB-PSiYqzTKNjF7_afRqcVCy72IkaUZP1Zr8kPCXRZ8mygltoP8jZy92zlTvQ&lib=MEKtXqESjgHfLHHki-QC018SoMAbC-O1l';

const MARATHONAPI='https://script.googleusercontent.com/macros/echo?user_content_key=4h_-27rI62OfAGSV2c29WtoCl6YETYCJX0vpDo1RMdnDwLvHKBNZNSLDWpbB83L-SyZigKFExh6ZeXoYSY24O3idT_syjHSvm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnIaViSFNVQZXawoto517r5wReIJEcf85lSrVGv5-jKGajKw4B2rlNHa5iJn66sSV0x53dkvwDeqiKtshBISUlPhedgLHmD5cLNz9Jw9Md8uu&lib=MIlvftCLwUMlWM4P90Cg59OzilWmV86UI';

const SERIESAPI='https://script.googleusercontent.com/macros/echo?user_content_key=cy9bom1bKXuTBJzfZO3tKWRCKOCPpo4XuRNPXugEJljbiu3J4HU8WBN6fkmv1vFQZOJEykHAv_lLI40xhzNBl4UZmzCwcsKGm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnEJXWTWEmQV3vbLisx1M41MVSPMIlvbgb7ret2IRQufM5It6i0QCerPYusNIyt1sw8McbxR9rEG9ov2vp85HxkuuwjhMb0MiNQ&lib=MwQgUIcuxmyXqt7kGj5PZ68SoMAbC-O1l';

const MOVIESPATH=`https://e-corpcompanygroupmovieslander.github.io/MovieLander/MoviesPosters/`;

const CATERGORYLINK='https://script.googleusercontent.com/macros/echo?user_content_key=73Zwb7PgOiKcWAkB8NtGkxfTc90BF9hrUmlWuNnkEviGIBt_rLKR5KcodIDbs_5XVUVVNmV5vcOK_WrIR7FWe5EXZUIScDyBm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnDAKcfISMWUvHYXMr5T0pgs4s_9FQHlxjb9feZm4btJ2cCHRmXMUjSkir9e7UGF7ELAFNcuA7nAFjqm93KgKPC3n5M9lbpsdpNz9Jw9Md8uu&lib=MFCxisweHYcb5KS6xW-H5O-zilWmV86UI';

const CATERGORIESPATH=`https://e-corpcompanygroupmovieslander.github.io/MovieLander/CATERGORIES/`;

const HELPTEXT=`https://e-corpcompanygroupmovieslander.github.io/MovieLander/HelpPage/HelpPage.txt`;

const UPDATE=`https://play.google.com/store/apps/details?id=com.ecorpcompanygroup.movie_lander`;

const PRIVACYTEXT=`https://e-corpcompanygroupmovieslander.github.io/MovieLander/PrivacyPolicyPage/PrivacyPolicy.txt`;

const PARENTALCONTROLTEXT=`https://e-corpcompanygroupmovieslander.github.io/MovieLander/ParentalControlPage/ParentalControl.txt`;

const MOREAPPSLINK=`https://script.googleusercontent.com/macros/echo?user_content_key=LKxwjuinC5ZmWbRncQj0nUwSwXKADTwv5xGfCCv3Tg7LguXyGjMS02QaDDfTOhCeQu5JNm8NUZSWOCRelh4h8pINjcWXmdUmm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnJAxInbGJwPEjZhGCuKhxCZeYLuntfgTpdBTwLd_e6uNDKcc-yF7VHtFnbexc1gXm5RC18NrtK2yu7TVI5lklsMMPmtozgPBbNz9Jw9Md8uu&lib=MzcnxIwsQ0SlCWA4i-RzuSuzilWmV86UI`;

const FREEMOVIESLINK=`https://script.googleusercontent.com/macros/echo?user_content_key=HKt-oFgq9a8pP6TFyPPkT_qhaTlGetxG2UYPkNQxW1_DqippS6C69CuSbjuKoWOY2MQtV7TGIaIn00_6n6HUrUIbtmWEb0A3m5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnG-yaZykjSDVpa22v3k4sN9hO6SWDHV_YK53U_Ee33aDg-Fk-JZJLpowmpSd2FzRq8YfXH-Sm77UiQMhAb443E7fniuLu6rw4tz9Jw9Md8uu&lib=M4nmkbmqn1uDLvVyEshwWJ-zilWmV86UI`;

const Termslinks='https://e-corpcompanygroupmovieslander.github.io/MovieLander/TermsAndConditionPage/TermsAndConditions.txt';

const ADVERTSPATH=`https://e-corpcompanygroupmovieslander.github.io/MovieLander/AdvertsImages/`;

export{LOGINAPI,ADVERTSAPI,ADVERTSPATH,ANIMATIONAPI,MOVIESPATH,SERIESAPI,MARATHONAPI,MOVIESAPI}