import * as ADVANCE from "../CONNECTION/Connection.js"
import { AUTOLOGINPAGE } from "../PAGES/AUTOLOGINPAGE/AutoLoginPage.js";

const CONNECTION=(DIV)=>{

    ADVANCE.OPERATINGSYSTEM();

    ADVANCE.ZOOMEFFECT();

    const ADD=ADVANCE.ADDPACKAGE;

    const CLEAR=ADVANCE.CLEARCOMPONENTS;

    const DISPLAY=ADVANCE.DISPLAYDATA;

    const ICONS=ADVANCE.ICONSPATH;

    console.log(ADVANCE);

    AUTOLOGINPAGE(DIV,ADVANCE,ADD,DISPLAY,CLEAR,ICONS);
    
}

export{CONNECTION}